### ISSUE TITLE
Maintenance and features

### ISSUE THREAD

**Issue by Bruce1979** [timur-tabi/svg-organizer#1]
Saw this on BGG and it worked a treat for one of my card games. Not sure if you're still working on this or not, but are you happy for me to contribute and make some of the following updates/features?

- Fix output error (number of slots has trailing mm e.g. num of slots: 9mm (should be 9))
- Allow user to enter a number of slots rather than a slot size through options
- Allow for uneven rows (e.g. box width = 300, row width = 120; generates outside rows of 120, inner row of 60)
- Possibility of adding a template for a removable storage box for inside a slot (not quite sure how this would work yet...)

As written the code works a treat, but these extra features would make it more flexible for a wider variety of storage options.

**Comment by timur-tabi** [comment]
Yes, I will gladly review and consider any pull requests you make.

**Comment by Bruce1979** [comment]
Decided to include a pull request for Python 3 conversion, number of slots option and multiple slot types (to allow for adjacency in both inner and outer rows). If you're willing to accept that one, I'll begin working on some other features that would be useful for some of the box designs I'd like for my own games (and would therefore print!)
